[package]
name = "dumpfuzzcator"
version = "0.1.0"
authors = ["Michael Voronin <mvoronin.ru@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
rand = "0.6.5"
rust-crypto = "0.2.36"
yaml-rust = "0.4.3"
