
transform:
  account_customuser:
    password: "!random<string>"
    email: "!random<email>"
  bundle_bundle:
    first_name: "!random<firstname>"
    last_name: "!random<lastname>"
    email: "!random<email>"
    dob: "!random<date>"
    address1: "!random<string:10>"
    city: "!random<string:3>"
    order_id: "!random<int>"
    fc_id: "!self<id>"
  kit_clinicalsite:
    address1: "!random<string:10>"
    city: "!random<string:5>"

ignore:
  - account_customuser_groups

remove:
  - django_admin_log
  - django_session

default: remove  # ignore | remove
